version: 0.0
os: linux
files:
  - source: /cluster_create.yml
    destination: /
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies
      timeout: 300
    - location: scripts/start_server
      timeout: 3000
  AfterInstall:
    - location: scripts/stop_server
      timeout: 3000
